name: reusable testing

on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
      build-type:
        required: true
        type: string
      cxx-standard:
        required: false
        type: number
      c-compiler:
        default: gcc
        type: string
      cxx-compiler:
        default: g++
        type: string
      use-valgrind:
        default: false
        type: boolean
      enable-sanitizers:
        default: false
        type: boolean
      build-only:
        default: false
        type: boolean

jobs:
  testing:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Clone the connector
        uses: actions/checkout@v3

      - name: Setup Tarantool
        if: ${{ !inputs.build-only }}
        uses: ./.github/actions/setup-tarantool
        with:
          runs-on: ${{ inputs.runs-on }}

      - name: Setup valgrind
        if: inputs.use-valgrind
        run: sudo apt update && sudo apt install -y valgrind

      # https://github.com/actions/runner-images/issues/8659
      - name: Remove incompatible libstdc++
        if: ${{ inputs.runs-on == 'ubuntu-22.04' && inputs.cxx-compiler == 'clang++' && inputs.cxx-standard == 20 }}
        run: |
          sudo apt remove gcc-13 g++-13 libstdc++-13-dev gcc g++ libstdc++-dev
          sudo apt autoremove
          sudo apt install g++-12

      - name: Build tntcxx
        uses: ./.github/actions/build-tntcxx
        with:
          build-type: ${{ inputs.build-type }}
          enable-sanitizers: ${{ inputs.enable-sanitizers }}
          cxx-standard: ${{ inputs.cxx-standard }}
          c-compiler: ${{ inputs.c-compiler }}
          cxx-compiler: ${{ inputs.cxx-compiler }}

      - name: Test tntcxx
        if: ${{ !inputs.build-only }}
        uses: ./.github/actions/test-tntcxx
        with:
          use-valgrind: ${{ inputs.use-valgrind }}
