name: reusable testing

on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
      build-type:
        required: true
        type: string
      use-valgrind:
        default: false
        type: boolean
      enable-sanitizers:
        default: false
        type: boolean

jobs:
  testing:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Clone the connector
        uses: actions/checkout@v3

      - name: Setup Tarantool
        uses: ./.github/actions/setup-tarantool
        with:
          runs-on: ${{ inputs.runs-on }}

      - name: Setup valgrind
        if: inputs.use-valgrind
        run: sudo apt update && sudo apt install -y valgrind

      - name: Build tntcxx
        uses: ./.github/actions/build-tntcxx
        with:
          build-type: ${{ inputs.build-type }}
          enable-sanitizers: ${{ inputs.enable-sanitizers }}

      - name: Test tntcxx
        uses: ./.github/actions/test-tntcxx
        with:
          use-valgrind: ${{ inputs.use-valgrind }}
